package com.scholarship.service;

import com.scholarship.model.EligibilityResponse;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * ScholarshipService.java  ← Service Endpoint Interface (SEI)
 * ─────────────────────────────────────────────────────────────
 * Defines the SOAP Web Service contract for the
 * Scholarship Eligibility Portal.
 *
 * WSDL is auto-generated by JAX-WS from these annotations.
 *
 * Operation:
 *   checkEligibility(name, marks, income, category)
 *        → EligibilityResponse (XML)
 * ─────────────────────────────────────────────────────────────
 */
@WebService(
    name            = "ScholarshipService",
    targetNamespace = "http://scholarship.com/service"
)
@SOAPBinding(style = SOAPBinding.Style.DOCUMENT)
public interface ScholarshipService {

    /**
     * Checks whether a student qualifies for any government
     * scholarship scheme based on the provided criteria.
     *
     * @param name          Student's full name
     * @param marks         Percentage marks obtained (0–100)
     * @param annualIncome  Family annual income in INR
     * @param category      Reservation category: GEN / OBC / SC / ST
     * @return EligibilityResponse with matched scholarships
     */
    @WebMethod(operationName = "checkEligibility",
               action        = "http://scholarship.com/service/checkEligibility")
    EligibilityResponse checkEligibility(
        @WebParam(name = "name")         String name,
        @WebParam(name = "marks")        double marks,
        @WebParam(name = "annualIncome") double annualIncome,
        @WebParam(name = "category")     String category
    );
}
